// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctdgfdlqzfgvbltifsud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZGdmZGxxemZndmJsdGlmc3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDk3NDcsImV4cCI6MjA2OTYyNTc0N30.jYhUiQVGbz46IR9Bbc91dn0AUU-5F0CsHCero-SA1Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});